const datainfo = [
  { type: "Veggie Burgers", price: 150, category: "Burger" },
  { type: "Chicken Burgers", price: 300, category: "Burger" },
  { type: "Bacon Cheeseburgers", price: 250, category: "Burger" },
  { type: "Classic Burger", price: 160, category: "Burger" },
  { type: "Humburger", price: 200, category: "Burger" },
  { type: "Grilled Chicken wraps", price: 160, category: "Sandwich" },
  { type: "Chicken Sandwich", price: 270, category: "Sandwich" },
  { type: "Wrap Sandwich", price: 260, category: "Sandwich" },
  { type: "Vegetable Sandwich", price: 160, category: "Sandwich" },
  { type: "Cheese Sandwich", price: 200, category: "Sandwich" },
  { type: "Traditional cutFries", price: 150, category: "Fries" },
  { type: "Waffle Fries", price: 130, category: "Fries" },
  { type: "Curly Fries", price: 120, category: "Fries" },
  { type: "Potato Wedges", price: 160, category: "Fries" },
  { type: "Masala Chips", price: 180, category: "Fries" },
  { type: "Pasta Alfredo", price: 400, category: "Pasta" },
  { type: "Pasta Bolognese", price: 450, category: "Pasta" },
  { type: "Spaghetti", price: 300, category: "Pasta" },
  { type: "Lasagna", price: 450, category: "Pasta" },
  { type: "Pasta with pesto", price: 550, category: "Pasta" },
  { type: "Grilled Chicken", price: 150, category: "Chicken" },
  { type: "Roasted Chicken", price: 250, category: "Chicken" },
  { type: "Spicy Wings", price: 350, category: "Chicken" },
  { type: "Buffalo wings", price: 450, category: "Chicken" },
  { type: "Chicken Lollipops", price: 550, category: "Chicken" },
  { type: "Minute Maid(all flavours)-small", price: 80, category: "Drinks" },
  { type: "Minute Maid(all flavours)-large", price: 140, category: "Drinks" },
  { type: "coke zero sugar-small", price: 80, category: "Drinks" },
  { type: "blackcurrent -1 litre", price: 100, category: "Drinks" },
  { type: "sprite - litre", price: 100, category: "Drinks" },
];
export default datainfo;
